## Multivariate Linear Regression
- Simple Linear Regression 복습
- Multivariate Linear Regression 이론
- Naive Data Representation
- Matrix Data Representation
- Multivariate Linear Regression 
- nn.Module 소개
- F.mse_loss 소개

### Simple Linear Regression

$ H(x) = Wx + b $

### Multivariate Linear Regression

$ H(x_1, x_2, x_3) = x_1w_1 + x_2w_2 + x_3w_3 + b $

$ cost(W, b) = \frac{1}{m} \sum^m_{i=1} \left( H(x^{(i)}) - y^{(i)} \right)^2 $

 - $H(x)$: 주어진 $x$ 값에 대해 예측을 어떻게 할 것인가
 - $cost(W, b)$: $H(x)$ 가 $y$ 를 얼마나 잘 예측했는가

### Naive Data Representation

In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [2]:
# For reproducibility
torch.manual_seed(1)

In [3]:
# 데이터
x1_train = torch.FloatTensor([[73], [93], [89], [96], [73]])
x2_train = torch.FloatTensor([[80], [88], [91], [98], [66]])
x3_train = torch.FloatTensor([[75], [93], [90], [100], [70]])
y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [4]:
# 모델 초기화
w1 = torch.zeros(1, requires_grad = True)
w2 = torch.zeros(1, requires_grad = True)
w3 = torch.zeros(1, requires_grad = True)
b = torch.zeros(1, requires_grad = True)

# optimizer
optimizer = optim.SGD([w1, w2, w3, b], lr = 1e-5)

epochs = 1000
for epoch in range(epochs + 1):
        # H(x) 계산
    hypothesis = x1_train * w1 + x2_train * w2 + x3_train * w3 + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} w1: {:.3f} w2: {:.3f} w3: {:.3f} b: {:.3f} Cost: {:.6f}'.format(
            epoch, epochs, w1.item(), w2.item(), w3.item(), b.item(), cost.item()
        ))

Epoch    0/1000 w1: 0.294 w2: 0.294 w3: 0.297 b: 0.003 Cost: 29661.800781
Epoch  100/1000 w1: 0.674 w2: 0.661 w3: 0.676 b: 0.008 Cost: 1.563628
Epoch  200/1000 w1: 0.679 w2: 0.655 w3: 0.677 b: 0.008 Cost: 1.497595
Epoch  300/1000 w1: 0.684 w2: 0.649 w3: 0.677 b: 0.008 Cost: 1.435044
Epoch  400/1000 w1: 0.689 w2: 0.643 w3: 0.678 b: 0.008 Cost: 1.375726
Epoch  500/1000 w1: 0.694 w2: 0.638 w3: 0.678 b: 0.009 Cost: 1.319507
Epoch  600/1000 w1: 0.699 w2: 0.633 w3: 0.679 b: 0.009 Cost: 1.266222
Epoch  700/1000 w1: 0.704 w2: 0.627 w3: 0.679 b: 0.009 Cost: 1.215703
Epoch  800/1000 w1: 0.709 w2: 0.622 w3: 0.679 b: 0.009 Cost: 1.167810
Epoch  900/1000 w1: 0.713 w2: 0.617 w3: 0.680 b: 0.009 Cost: 1.122429
Epoch 1000/1000 w1: 0.718 w2: 0.613 w3: 0.680 b: 0.009 Cost: 1.079390


### Full Code with torch.optim

In [5]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [6]:
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])

y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

In [7]:
x_train.shape

torch.Size([5, 3])

In [8]:
# 모델 초기화
W = torch.zeros((x_train.shape[1], 1), requires_grad = True)
b = torch.zeros(1, requires_grad = True)

# optimizer 설정
optimizer = optim.SGD([W, b], lr = 1e-5)

epochs = 20
for epoch in range(epochs + 1):
    # H(x) 계산
    hypothesis = x_train.matmul(W) + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    
    print('Epoch [{:4d}/{}] hypothesis: {} Cost: {:.6f}'.format(
        epoch, epochs, hypothesis.squeeze().detach(), cost.item()
    ))

Epoch [   0/20] hypothesis: tensor([0., 0., 0., 0., 0.]) Cost: 29661.800781
Epoch [   1/20] hypothesis: tensor([67.2578, 80.8397, 79.6523, 86.7394, 61.6605]) Cost: 9298.520508
Epoch [   2/20] hypothesis: tensor([104.9128, 126.0990, 124.2466, 135.3015,  96.1821]) Cost: 2915.712402
Epoch [   3/20] hypothesis: tensor([125.9942, 151.4381, 149.2133, 162.4896, 115.5097]) Cost: 915.040527
Epoch [   4/20] hypothesis: tensor([137.7967, 165.6247, 163.1911, 177.7112, 126.3307]) Cost: 287.936096
Epoch [   5/20] hypothesis: tensor([144.4044, 173.5674, 171.0168, 186.2332, 132.3891]) Cost: 91.371063
Epoch [   6/20] hypothesis: tensor([148.1035, 178.0143, 175.3980, 191.0042, 135.7812]) Cost: 29.758249
Epoch [   7/20] hypothesis: tensor([150.1744, 180.5042, 177.8509, 193.6753, 137.6805]) Cost: 10.445267
Epoch [   8/20] hypothesis: tensor([151.3336, 181.8983, 179.2240, 195.1707, 138.7440]) Cost: 4.391237
Epoch [   9/20] hypothesis: tensor([151.9824, 182.6789, 179.9928, 196.0079, 139.3396]) Cost: 2.49312

In [9]:
hypothesis

tensor([[152.8020],
        [183.6731],
        [180.9677],
        [197.0699],
        [140.0999]], grad_fn=<AddBackward0>)

In [10]:
hypothesis.shape

torch.Size([5, 1])

In [11]:
hypothesis.squeeze()

tensor([152.8020, 183.6731, 180.9677, 197.0699, 140.0999],
       grad_fn=<SqueezeBackward0>)

In [12]:
hypothesis.squeeze().shape

torch.Size([5])

In [13]:
hypothesis.squeeze().detach()

tensor([152.8020, 183.6731, 180.9677, 197.0699, 140.0999])

### High-level Implementation with nn.Module

In [14]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

class LinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(1, 1) # 1은 w1 가중치 개수 단순선형회귀라 하나일수 밖에...

    def forward(self, x):
        return self.linear(x)

class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1) # 3은 w1, w2, w3 가중치 개수 다중선형회귀
    
    def forward(self, x):
        return self.linear(x)

In [15]:
# 데이터
x_train = torch.FloatTensor([[73, 80, 75],
                             [93, 88, 93],
                             [89, 91, 90],
                             [96, 98, 100],
                             [73, 66, 70]])

y_train = torch.FloatTensor([[152], [185], [180], [196], [142]])

# 모델 초기화
# W = torch.zeros((x_train.shape[1], 1), requires_grad = True)
# b = torch.zeros(1, requires_grad = True)
model = MultivariateLinearRegressionModel()

# optimizer 설정
# optimizer = optim.SGD([W, b], lr = 1e-5)
optimizer = optim.SGD(model.parameters(), lr=1e-5)

epochs = 20
for epoch in range(epochs + 1):
    # H(x) 계산
    pred = model(x_train)

    # cost 계산
    cost = F.mse_loss(pred, y_train)
    
    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch [{:4d}/{}] pred: {} Cost: {:.6f}'.format(
        epoch, epochs, pred.squeeze().detach(), cost.item()
    ))

Epoch [   0/20] pred: tensor([-6.7933, -4.8968, -6.5155, -7.3361, -2.6660]) Cost: 31667.597656
Epoch [   1/20] pred: tensor([62.7036, 78.6331, 75.7880, 82.2903, 61.0462]) Cost: 9926.265625
Epoch [   2/20] pred: tensor([101.6124, 125.3983, 121.8667, 132.4688,  96.7163]) Cost: 3111.513672
Epoch [   3/20] pred: tensor([123.3960, 151.5805, 147.6645, 160.5620, 116.6867]) Cost: 975.451477
Epoch [   4/20] pred: tensor([135.5919, 166.2389, 162.1078, 176.2903, 127.8673]) Cost: 305.908630
Epoch [   5/20] pred: tensor([142.4199, 174.4456, 170.1940, 185.0960, 134.1269]) Cost: 96.042679
Epoch [   6/20] pred: tensor([146.2428, 179.0401, 174.7212, 190.0260, 137.6314]) Cost: 30.260782
Epoch [   7/20] pred: tensor([148.3830, 181.6125, 177.2559, 192.7861, 139.5934]) Cost: 9.641681
Epoch [   8/20] pred: tensor([149.5813, 183.0526, 178.6749, 194.3314, 140.6919]) Cost: 3.178685
Epoch [   9/20] pred: tensor([150.2523, 183.8588, 179.4694, 195.1966, 141.3068]) Cost: 1.152871
Epoch [  10/20] pred: tensor([150.

### Loading Data from .csv file (github)


In [16]:
!git clone https://github.com/yeonwoo780/deeplearning_basic.git

fatal: destination path 'deeplearning_basic' already exists and is not an empty directory.


In [17]:
!ls -lia
!ls -lia deeplearning_basic
!ls -lia deeplearning_basic/Pytorch_dataset

total 20
4849688 drwxr-xr-x 1 root root 4096 Jun  4 00:55 .
4457573 drwxr-xr-x 1 root root 4096 Jun  3 23:56 ..
6553616 drwxr-xr-x 4 root root 4096 Jun  1 13:40 .config
4457579 drwxr-xr-x 7 root root 4096 Jun  4 00:55 deeplearning_basic
4849689 drwxr-xr-x 1 root root 4096 Jun  1 13:40 sample_data
total 40
4457579 drwxr-xr-x 7 root root 4096 Jun  4 00:55 .
4849688 drwxr-xr-x 1 root root 4096 Jun  4 00:55 ..
4457700 drwxr-xr-x 5 root root 4096 Jun  4 00:55 Chapter10~19
4457763 drwxr-xr-x 2 root root 4096 Jun  4 00:55 Chapter1~9
4457779 drwxr-xr-x 2 root root 4096 Jun  4 00:55 dataset
4457580 drwxr-xr-x 8 root root 4096 Jun  4 00:55 .git
4457679 -rw-r--r-- 1 root root   13 Jun  4 00:55 .gitignore
4457773 drwxr-xr-x 2 root root 4096 Jun  4 00:55 Pytorch_dataset
4457786 -rw-r--r-- 1 root root  392 Jun  4 00:55 pyvenv.cfg
4457778 -rw-r--r-- 1 root root 3326 Jun  4 00:55 README.md
total 112
4457773 drwxr-xr-x 2 root root  4096 Jun  4 00:55 .
4457579 drwxr-xr-x 7 root root  4096 Jun  4 00:55 .

In [18]:
!pwd

/content


In [19]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import numpy as np
import os

# For reproducibility
torch.manual_seed(1)

xy = np.loadtxt('/content/deeplearning_basic/Pytorch_dataset/data-01-test-score.csv', 
                delimiter = ',', dtype = np.float32)

In [20]:
x_data = xy[:, :-1]
x_data

array([[ 73.,  80.,  75.],
       [ 93.,  88.,  93.],
       [ 89.,  91.,  90.],
       [ 96.,  98., 100.],
       [ 73.,  66.,  70.],
       [ 53.,  46.,  55.],
       [ 69.,  74.,  77.],
       [ 47.,  56.,  60.],
       [ 87.,  79.,  90.],
       [ 79.,  70.,  88.],
       [ 69.,  70.,  73.],
       [ 70.,  65.,  74.],
       [ 93.,  95.,  91.],
       [ 79.,  80.,  73.],
       [ 70.,  73.,  78.],
       [ 93.,  89.,  96.],
       [ 78.,  75.,  68.],
       [ 81.,  90.,  93.],
       [ 88.,  92.,  86.],
       [ 78.,  83.,  77.],
       [ 82.,  86.,  90.],
       [ 86.,  82.,  89.],
       [ 78.,  83.,  85.],
       [ 76.,  83.,  71.],
       [ 96.,  93.,  95.]], dtype=float32)

In [21]:
y_data = xy[:, [-1]]
y_data

array([[152.],
       [185.],
       [180.],
       [196.],
       [142.],
       [101.],
       [149.],
       [115.],
       [175.],
       [164.],
       [141.],
       [141.],
       [184.],
       [152.],
       [148.],
       [192.],
       [147.],
       [183.],
       [177.],
       [159.],
       [177.],
       [175.],
       [175.],
       [149.],
       [192.]], dtype=float32)

In [22]:
print(x_data.shape) # x_data shape
print(len(x_data))  # x_data 길이

(25, 3)
25


In [23]:
print(y_data.shape) # y_data shape
print(len(y_data))  # y_data 길이

(25, 1)
25


### Low-level Implementation

In [24]:
# 데이터
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

# 모델 초기화
W = torch.zeros((x_data.shape[1], 1), requires_grad = True)
b = torch.zeros(1, requires_grad = True)

# optimizer 설정
optimizer = optim.SGD([W, b], lr = 1e-5)

epochs = 20
for epoch in range(epochs + 1):
    # H(x) 계산
    hypothesis = x_train.matmul(W) + b

    # cost 계산
    cost = torch.mean((hypothesis - y_train) ** 2)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    # 
    print('Epoch {:4d}/{} hypothesis: {} Cost: {:.6f}'.format(
        epoch, epochs, hypothesis.squeeze().detach(), cost.item()
    ))

Epoch    0/20 hypothesis: tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.]) Cost: 26811.960938
Epoch    1/20 hypothesis: tensor([60.3300, 72.5121, 71.4468, 77.8114, 55.3021, 40.7728, 58.2450, 43.1798,
        67.7684, 62.7711, 56.1159, 55.3320, 73.8140, 61.3605, 58.5129, 73.5830,
        58.4375, 69.8998, 70.3709, 62.9651, 68.3015, 68.0264, 65.1199, 60.8261,
        75.1500]) Cost: 9920.530273
Epoch    2/20 hypothesis: tensor([ 97.0136, 116.6032, 114.8901, 125.1249,  88.9286,  65.5651,  93.6612,
         69.4359, 108.9755, 100.9401,  90.2374,  88.9771, 118.6964,  98.6703,
         94.0921, 118.3256,  93.9699, 112.4028, 113.1596, 101.2509, 109.8326,
        109.3903, 104.7163,  97.8108, 120.8450]) Cost: 3675.298340
Epoch    3/20 hypothesis: tensor([119.3189, 143.4130, 141.3056, 153.8940, 109.3753,  80.6404, 115.1964,
         85.4014, 134.0320, 124.1496, 110.9851, 109.4354, 145.9869, 121.3560,
        115.7265, 145.5315,

### High-level Implementation with nn.Module

In [25]:
class MultivariateLinearRegressionModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.linear = nn.Linear(3, 1) # 3은 w1, w2, w3 가중치 개수 다중선형회귀

    def forward(self, x):
        return self.linear(x)

In [26]:
# 데이터
x_train = torch.FloatTensor(x_data)
y_train = torch.FloatTensor(y_data)

# 모델 초기화
# W = torch.zeros((x_train.shape[1], 1), requires_grad = True)
# b = torch.zeros(1, requires_grad = True)
model = MultivariateLinearRegressionModel()

# optimizer 설정
# optimizer = optim.SGD([W, b], lr = 1e-5)
optimizer = optim.SGD(model.parameters(), lr = 1e-5)

epochs = 20
for epoch in range(epochs + 1):
    # H(x) 계산
    pred = model(x_train)

    # cost 계산
    cost = F.mse_loss(pred, y_train)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    cost.backward()
    optimizer.step()

    print('Epoch {:4d}/{} Cost: {:.6f}'.format(
        epoch, epochs, cost.item()
    ))    

Epoch    0/20 Cost: 28693.490234
Epoch    1/20 Cost: 10618.750000
Epoch    2/20 Cost: 3936.015381
Epoch    3/20 Cost: 1465.219727
Epoch    4/20 Cost: 551.693726
Epoch    5/20 Cost: 213.934616
Epoch    6/20 Cost: 89.052269
Epoch    7/20 Cost: 42.876007
Epoch    8/20 Cost: 25.799639
Epoch    9/20 Cost: 19.482420
Epoch   10/20 Cost: 17.143093
Epoch   11/20 Cost: 16.274508
Epoch   12/20 Cost: 15.949721
Epoch   13/20 Cost: 15.825986
Epoch   14/20 Cost: 15.776565
Epoch   15/20 Cost: 15.754660
Epoch   16/20 Cost: 15.742919
Epoch   17/20 Cost: 15.734917
Epoch   18/20 Cost: 15.728307
Epoch   19/20 Cost: 15.722219
Epoch   20/20 Cost: 15.716357


In [27]:
pred.squeeze().detach()

tensor([152.4213, 186.4618, 182.0337, 198.0186, 143.2669, 105.7658, 147.0534,
        107.2567, 174.7979, 161.7666, 142.8898, 142.2821, 188.3299, 157.1252,
        148.2012, 188.7067, 150.9361, 175.5236, 179.0799, 159.8652, 172.9467,
        174.5278, 164.6813, 154.2838, 192.8142])